branches:
  - main
  - name: develop
    prerelease: rc
    channel: next

preset: "conventionalcommits"
tagFormat: "v${version}${ process.env.GOV === 'true' ? '+gov' : '' }"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@saithodev/semantic-release-backmerge"
  - "@semantic-release/github"

verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - path: "@saithodev/semantic-release-backmerge"
    branches:
      - from: main
        to: stage
    backmergeStrategy: merge

prepare:
  - "@semantic-release/changelog"

publish:
  - "@semantic-release/github"

success:
  - path: "@saithodev/semantic-release-backmerge"
    branches:
      - from: main
        to: stage
    backmergeStrategy: merge