branches:
  - main
  - name: stage
    prerelease: rc
    channel: next

preset: "conventionalcommits"
tagFormat: "v${version}${ process.env.GOV === 'true' ? '+gov' : '' }"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@saithodev/semantic-release-backmerge"
    - backmergeBranches:
      - from: main
        to: stage
      backmergeStrategy: merge

verifyConditions:
  - "@semantic-release/changelog"
  - "@semantic-release/git"

prepare:
  - "@semantic-release/changelog"

publish:
  - "@semantic-release/github"

success: