name: Semantic Release

on:
  push:
    branches:
      - main
      - stage
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      GOV: ${{ steps.resolve-env.outputs.GOV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - id: resolve-env
        name: Resolve ENV
        run: |
          env
          GOV=$(gh api /repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/pulls --jq 'map(.labels) | flatten | [.[] | select(.name == "gov-deploy")] | length')
          echo $GOV
          # gov env out
          if [[ $GOV -eq 1 ]]; then
            echo "in if statement"
            echo "gov=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOV: ${{ steps.resolve-env.outputs.gov }}

      - name: github script test
        id: github-script
        uses: actions/github-script@v7
        with:
          script: |
            console.log("context", JSON.stringify(context, null, 2));
            console.log("github", JSON.stringify(github, null, 2));
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              tag: "v1.2.0-rc.17"
            })

            console.log(release.data)
            const newBody = `${release.data.body}
            ### modusign-gov tenant deployment log
            [gov-deployed]
            [![Workflow Dispatch](${context.payload.repository.html_url}/actions/workflows/${}.yaml/badge.svg?branch=${release.data.tag_name})](${context.payload.repository.html_url}/actions/runs/${context.runId})
            `

            await github.rest.repos.updateRelease({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              release_id: release.data.id,
              body: newBody
            });
