name: Semantic Release

on:
  push:
    branches:
      - main
      - stage
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    # outputs:
    #   GOV: ${{ steps.resolve-env.outputs.GOV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Resolve ENV
        run: |
          env
          echo 123
        #   gh api /repos/modusign/approval/commits/3c01df5/pulls --jq '.[0].labels | .[] | select(.default == false)'
        #   gh api /repos/modusign/approval/commits/3c01df5/pulls --jq '.[0].labels | .[] | select(.default == false)'

      - name: Semantic Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOV: ${{ (startsWith(github.ref, 'refs/heads/develop') && 'true') || 'false' }}
